// Sudan States and Localities
class SudanLocations {
  static const Map<String, List<String>> statesWithLocalities = {
    'الخرطوم': [
      'الخرطوم',
      'أم درمان',
      'بحري',
      'كرري',
      'أم بدة',
      'شرق النيل',
      'جبل أولياء',
    ],
    'الجزيرة': [
      'ود مدني',
      'الكاملين',
      'الحصاحيصا',
      'المناقل',
      'الهلالية',
      'جنوب الجزيرة',
      'أم القرى',
    ],
    'نهر النيل': [
      'الدامر',
      'عطبرة',
      'شندي',
      'بربر',
      'أبو حمد',
      'المتمة',
    ],
    'الشمالية': [
      'دنقلا',
      'مروي',
      'كريمة',
      'دلقو',
      'حلفا',
    ],
    'كسلا': [
      'كسلا',
      'حلفا الجديدة',
      'خشم القربة',
      'ود الحليو',
      'أروما',
      'تلكوك',
      'همشكوريب',
    ],
    'القضارف': [
      'القضارف',
      'قلع النحل',
      'الفاو',
      'الفشقة',
      'القريشة',
      'الرهد',
    ],
    'البحر الأحمر': [
      'بورتسودان',
      'سواكن',
      'طوكر',
      'هيا',
      'جبيت',
      'سنكات',
    ],
    'سنار': [
      'سنار',
      'سنجة',
      'الدندر',
      'الدالي والمزموم',
    ],
    'النيل الأزرق': [
      'الدمازين',
      'الروصيرص',
      'باو',
      'قيسان',
    ],
    'النيل الأبيض': [
      'ربك',
      'كوستي',
      'الدويم',
      'تندلتي',
      'أم رمتة',
      'الجزيرة أبا',
    ],
    'شمال كردفان': [
      'الأبيض',
      'شيكان',
      'أم روابة',
      'النهود',
      'بارا',
      'جبرة الشيخ',
      'سودري',
    ],
    'جنوب كردفان': [
      'كادقلي',
      'الدلنج',
      'أبو جبيهة',
      'تلودي',
      'رشاد',
      'الليري',
    ],
    'غرب كردفان': [
      'الفولة',
      'النهود',
      'أبو زبد',
      'المجلد',
      'لقاوة',
    ],
    'شمال دارفور': [
      'الفاشر',
      'كتم',
      'كبكابية',
      'أم كدادة',
      'الكومة',
      'طويلة',
      'مليط',
    ],
    'جنوب دارفور': [
      'نيالا',
      'كاس',
      'مرشنج',
      'قريضة',
      'تلس',
      'عد الفرسان',
      'شعيرية',
    ],
    'غرب دارفور': [
      'الجنينة',
      'زالنجي',
      'كرينك',
      'سربا',
      'هبيلا',
    ],
    'وسط دارفور': [
      'زالنجي',
      'نرتتي',
      'أم دخن',
      'أزوم',
      'بندسي',
    ],
    'شرق دارفور': [
      'الضعين',
      'أبو كارنكا',
      'عديلة',
      'شعيرية',
      'أبو جابرة',
    ],
  };

  static List<String> get states => statesWithLocalities.keys.toList();

  static List<String> getLocalities(String state) {
    return statesWithLocalities[state] ?? [];
  }

  static const Map<String, String> _statesEn = {
    'الخرطوم': 'Khartoum',
    'الجزيرة': 'Al Jazirah',
    'نهر النيل': 'River Nile',
    'الشمالية': 'Northern',
    'كسلا': 'Kassala',
    'القضارف': 'Al Qadarif',
    'البحر الأحمر': 'Red Sea',
    'سنار': 'Sennar',
    'النيل الأزرق': 'Blue Nile',
    'النيل الأبيض': 'White Nile',
    'شمال كردفان': 'North Kurdufan',
    'جنوب كردفان': 'South Kurdufan',
    'غرب كردفان': 'West Kurdufan',
    'شمال دارفور': 'North Darfur',
    'جنوب دارفور': 'South Darfur',
    'غرب دارفور': 'West Darfur',
    'وسط دارفور': 'Central Darfur',
    'شرق دارفور': 'East Darfur',
  };

  static const Map<String, String> _localitiesEn = {
    'الخرطوم': 'Khartoum',
    'أم درمان': 'Omdurman',
    'بحري': 'Bahri',
    'كرري': 'Karari',
    'أم بدة': 'Umbadda',
    'شرق النيل': 'Sharg En Nile',
    'جبل أولياء': 'Jebel Aulia',
    'ود مدني': 'Wad Madani',
    'الكاملين': 'Al Kamlin',
    'الحصاحيصا': 'Al Hasaheisa',
    'المناقل': 'Al Managil',
    'الهلالية': 'Al Hilaliya',
    'جنوب الجزيرة': 'South Jazirah',
    'أم القرى': 'Umm Al Qura',
    'الدامر': 'Ad Damar',
    'عطبرة': 'Atbara',
    'شندي': 'Shendi',
    'بربر': 'Berber',
    'أبو حمد': 'Abu Hamad',
    'المتمة': 'Al Matamma',
    'دنقلا': 'Dongola',
    'مروي': 'Merowe',
    'كريمة': 'Karima',
    'دلقو': 'Delgo',
    'حلفا': 'Halfa',
    'كسلا': 'Kassala',
    'حلفا الجديدة': 'New Halfa',
    'خشم القربة': 'Khashm el Girba',
    'ود الحليو': 'Wad el Helew',
    'أروما': 'Aroma',
    'تلكوك': 'Telkok',
    'همشكوريب': 'Hamesh Koreb',
    'القضارف': 'Al Qadarif',
    'قلع النحل': 'Gala An Nahl',
    'الفاو': 'Al Faw',
    'الفشقة': 'Al Fashqa',
    'القريشة': 'Al Guraisha',
    'الرهد': 'Ar Rahad',
    'بورتسودان': 'Port Sudan',
    'سواكن': 'Suakin',
    'طوكر': 'Tokar',
    'هيا': 'Haya',
    'جبيت': 'Jabeet',
    'سنكات': 'Sinkat',
    'سنار': 'Sennar',
    'سنجة': 'Singa',
    'الدندر': 'Dinder',
    'الدالي والمزموم': 'Ad Dali & Al Mazmum',
    'الدمازين': 'Ed Damazin',
    'الروصيرص': 'Er Roseires',
    'باو': 'Baw',
    'قيسان': 'Geissan',
    'ربك': 'Rabak',
    'كوستي': 'Kosti',
    'الدويم': 'Ad Duwem',
    'تندلتي': 'Tendelti',
    'أم رمتة': 'Um Remta',
    'الجزيرة أبا': 'Aba Island',
    'الأبيض': 'El Obeid',
    'شيكان': 'Sheikan',
    'أم روابة': 'Um Ruwaba',
    'النهود': 'En Nahud',
    'بارا': 'Bara',
    'جبرة الشيخ': 'Gebra El Sheikh',
    'سودري': 'Sodari',
    'كادقلي': 'Kadugli',
    'الدلنج': 'Dilling',
    'أبو جبيهة': 'Abu Jubaiyah',
    'تلودي': 'Talodi',
    'رشاد': 'Rashad',
    'الليري': 'El Liri',
    'الفولة': 'Al Fula',
    'أبو زبد': 'Abu Zabad',
    'المجلد': 'Al Mujlad',
    'لقاوة': 'Lagawa',
    'الفاشر': 'El Fasher',
    'كتم': 'Kutum',
    'كبكابية': 'Kabkabiya',
    'أم كدادة': 'Umm Kadada',
    'الكومة': 'Al Koma',
    'طويلة': 'Tawila',
    'مليط': 'Mellit',
    'نيالا': 'Nyala',
    'كاس': 'Kass',
    'مرشنج': 'Mershing',
    'قريضة': 'Gereida',
    'تلس': 'Tulus',
    'عد الفرسان': 'Idd al Fursan',
    'شعيرية': 'Shearia',
    'الجنينة': 'Geneina',
    'زالنجي': 'Zalingei',
    'كرينك': 'Kreanik',
    'سربا': 'Sirba',
    'هبيلا': 'Habila',
    'نرتتي': 'Nertiti',
    'أم دخن': 'Um Dukhun',
    'أزوم': 'Azum',
    'بندسي': 'Bindisi',
    'الضعين': 'Ed Daein',
    'أبو كارنكا': 'Abu Karinka',
    'عديلة': 'Adila',
    'أبو جابرة': 'Abu Jabra',
  };

  static String getStateName(String state, String locale) {
    if (locale == 'en') return _statesEn[state] ?? state;
    return state;
  }

  static String getLocalityName(String locality, String locale) {
    if (locale == 'en') return _localitiesEn[locality] ?? locality;
    return locality;
  }
}
