import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/constants/app_colors.dart';
import '../../core/utils/app_error_handler.dart';
import '../../providers/auth_provider.dart';
import '../../providers/locale_provider.dart';
import '../../models/report_model.dart';
import '../../models/user_model.dart';
import '../../models/notification_model.dart';
import '../../services/firestore_service.dart';
import '../../services/cloudinary_service.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:io';
import 'package:image_picker/image_picker.dart';

import '../../widgets/buttons/primary_button.dart';
import '../../widgets/inputs/custom_text_field.dart';

class ReportDialog extends StatefulWidget {
  final UserModel reportedUser;

  const ReportDialog({super.key, required this.reportedUser});

  @override
  State<ReportDialog> createState() => _ReportDialogState();
}

class _ReportDialogState extends State<ReportDialog> {
  final _reasonController = TextEditingController();
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;
  File? _imageFile;

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final pickedFile =
        await picker.pickImage(source: ImageSource.gallery, imageQuality: 70);
    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path);
      });
    }
  }

  @override
  void dispose() {
    _reasonController.dispose();
    super.dispose();
  }

  Future<void> _submitReport() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    final currentUser = context.read<AuthProvider>().user!;
    final navigator = Navigator.of(context);
    final messenger = ScaffoldMessenger.of(context);
    final locale = context.read<LocaleProvider>().locale.languageCode;

    try {
      String? uploadedImageUrl;
      if (_imageFile != null) {
        uploadedImageUrl = await CloudinaryService().uploadImage(_imageFile!);
      }

      final report = ReportModel(
        id: '', // Generated by Firestore
        reporterId: currentUser.id,
        reporterName: currentUser.name,
        reportedUserId: widget.reportedUser.id,
        reportedUserName: widget.reportedUser.name,
        reportedUserPhone: widget.reportedUser.phoneNumber,
        reason: _reasonController.text.trim(),
        imageUrl: uploadedImageUrl,
        createdAt: DateTime.now(),
      );

      await FirestoreService().submitReport(report);

      // Create a notification for the reporter promising a 24h response
      final notifRef =
          FirebaseFirestore.instance.collection('notifications').doc();
      final notification = NotificationModel(
        id: notifRef.id,
        userId: currentUser.id,
        type: NotificationType.system,
        title: locale == 'ar' ? 'تم استلام بلاغك 🛡️' : 'Report Received 🛡️',
        message: locale == 'ar'
            ? 'شكراً لتعاونك. قمنا باستلام بلاغك ضد "${widget.reportedUser.name}" وسنقوم بالرد وإتخاذ الإجراء اللازم خلال 24 ساعة.'
            : 'Thank you. We received your report against "${widget.reportedUser.name}" and will take action within 24 hours.',
        createdAt: Timestamp.now(),
        relatedId: report.id,
      );
      await notifRef.set(notification.toFirestore());

      if (mounted) {
        navigator.pop();
        messenger.showSnackBar(
          SnackBar(
            content: Text(
              locale == 'ar'
                  ? 'تم إرسال البلاغ بنجاح وسقوم الإدارة بمراجعته'
                  : 'Report submitted successfully and will be reviewed',
            ),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e, stack) {
      if (mounted) {
        await AppErrorHandler.show(
          context,
          e,
          stack,
          logContext: 'ReportDialog._submitReport',
          customMessage: locale == 'ar'
              ? 'فشل إرسال البلاغ. يرجى المحاولة مرة أخرى.'
              : 'Failed to submit report. Please try again.',
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final locale = context.watch<LocaleProvider>().locale.languageCode;
    final isAr = locale == 'ar';

    return AlertDialog(
      title: Row(
        children: [
          Icon(Icons.report_problem, color: AppColors.error),
          const SizedBox(width: 8),
          Text(isAr ? 'إبلاغ عن مستخدم' : 'Report User'),
        ],
      ),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                isAr
                    ? 'أنت على وشك الإبلاغ عن "${widget.reportedUser.name}". يرجى ذكر السبب بوضوح.'
                    : 'You are reporting "${widget.reportedUser.name}". Please state the reason clearly.',
                style: Theme.of(context).textTheme.bodyMedium,
              ),
              const SizedBox(height: 16),
              CustomTextField(
                label: isAr ? 'سبب البلاغ' : 'Reason',
                hint: isAr
                    ? 'اشرح المشكلة بالتفصيل...'
                    : 'Explain the issue in detail...',
                controller: _reasonController,
                maxLines: 4,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return isAr ? 'هذا الحقل مطلوب' : 'This field is required';
                  }
                  if (value.length < 10) {
                    return isAr
                        ? 'يرجى كتابة تفاصيل أكثر'
                        : 'Please provide more details';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 12),
              GestureDetector(
                onTap: _pickImage,
                child: Container(
                  height: 100,
                  width: double.infinity,
                  decoration: BoxDecoration(
                    color: Colors.grey[200],
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: Colors.grey[400]!),
                    image: _imageFile != null
                        ? DecorationImage(
                            image: FileImage(_imageFile!),
                            fit: BoxFit.cover,
                          )
                        : null,
                  ),
                  child: _imageFile == null
                      ? Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(Icons.add_photo_alternate,
                                color: Colors.grey, size: 30),
                            const SizedBox(height: 4),
                            Text(
                                isAr
                                    ? 'إضافة صورة (لقطة شاشة) - اختياري'
                                    : 'Add screenshot (optional)',
                                style: const TextStyle(color: Colors.grey)),
                          ],
                        )
                      : Align(
                          alignment: Alignment.topRight,
                          child: IconButton(
                            icon: const Icon(Icons.cancel, color: Colors.red),
                            onPressed: () => setState(() => _imageFile = null),
                          ),
                        ),
                ),
              ),
              const SizedBox(height: 8),
              if (widget.reportedUser.phoneNumber != null)
                Text(
                  isAr
                      ? 'سيتم إرفاق رقم هاتف المستخدم تلقائياً مع البلاغ.'
                      : 'User phone number will be automatically attached.',
                  style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text(isAr ? 'إلغاء' : 'Cancel'),
        ),
        SizedBox(
          width: 100,
          child: GradientButton(
            text: isAr ? 'إرسال' : 'Submit',
            onPressed: _submitReport,
            isLoading: _isLoading,
            gradientColors: [
              AppColors.error,
              AppColors.error.withValues(alpha: 0.8)
            ],
          ),
        ),
      ],
    );
  }
}
